<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="Tester-PC" failures="1" tests="2" name="Receipt_Day_Book_Report" time="24.034" errors="0" timestamp="10 Aug 2018 09:22:45 GMT">
  <testcase classname="com.mytest.Receipt_Day_Book_Report" name="Add_Account_Head" time="12.353"/>
  <testcase classname="com.mytest.Receipt_Day_Book_Report" name="Cash_Payment_Mode" time="11.654">
    <failure type="java.lang.AssertionError" message="Transaction Date NOT Getting Saved expected [10/08/2018] but found [Loading data from server]">
      <![CDATA[java.lang.AssertionError: Transaction Date NOT Getting Saved expected [10/08/2018] but found [Loading data from server]
at com.mytest.Receipt_Day_Book_Report.Cash_Payment_Mode(Receipt_Day_Book_Report.java:62)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- Cash_Payment_Mode -->
  <testcase classname="com.mytest.Login" name="login" time="0.0">
    <ignored/>
  </testcase> <!-- login -->
  <testcase classname="com.mytest.Receipt_Day_Book_Report" name="Online_Payment_Mode" time="0.0">
    <ignored/>
  </testcase> <!-- Online_Payment_Mode -->
  <testcase classname="com.mytest.Receipt_Day_Book_Report" name="Cheque_Payment_Mode" time="0.0">
    <ignored/>
  </testcase> <!-- Cheque_Payment_Mode -->
</testsuite> <!-- Receipt_Day_Book_Report -->
